# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZA2RDRcd4zp_PxRdja-T8Z13z399gYL
"""

try:

  result = 10 / 0
except ZeroDivisionError:
  print("Error: Division by zero")
except Exception as e:
  print(f"An unexpected error occurred: {e}")
else:
  print(f"Result: {result}")
finally:
  print("This always executes")