# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZA2RDRcd4zp_PxRdja-T8Z13z399gYL
"""

def read_numbers_from_file(filename):
    try:
        with open(filename, 'r') as file:
            numbers = [int(line.strip()) for line in file]
            print("Numbers in file:", numbers)
    except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found.")
    except ValueError:
        print("Error: The file contains non-numeric data.")

if __name__ == "__main__":
    filename = input("Enter the filename: ")
    read_numbers_from_file(filename)