# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZA2RDRcd4zp_PxRdja-T8Z13z399gYL
"""

import json
with open("data.json", "r") as file:
    data = json.load(file)
print(json.dumps(data, indent=4))